### ISSUE TITLE
Figure out how to recover login page to the right style

### ISSUE THREAD

**Issue by biz2013** [biz2013/xwjy#52]
For our release, the registration and login page need to look professional.
Before we use Boost style (stuff you commented out), now the Django form disturbed that.  Need to find a way to format it in Boost style (search w3school Boost 3 to study)
In addition, everything need to be Chinese.
 
Let's use Login page as test ground, then we change registration.

**Comment by biz2013** [comment]
@wcAlex I would think fix Login and Registration page style is more important then other P1 tasks.  We need to give our partner reasonable first impression.

**Comment by wcAlex** [comment]
@biz2013  Sure I will spend sometime today to learn boostrap and fix these right after. Expect to spend 1-2 days as I have forget all these JS.
Also I will define html template which could ensure our UI experience are unitied.

**Comment by biz2013** [comment]
generally it is fine.
